### ISSUE TITLE
Error running phybreak2.maf_to_fasta.py

### ISSUE THREAD

**Issue by asierzaragoza** [philarevalo/PopCOGenT#10]
Hello! I'm having an issue trying to run the core_gene_sweeps module. The error I get is: 
```
Traceback (most recent call last):
  File "phybreak2.maf_to_fasta.py", line 343, in <module>
    corefile.write(">"+iso +"\n"+ full_seqdict[iso] +"\n")
KeyError: 'IRLA172'
```
However, the genome in particular is found in both the 'strain_names.txt' file and in the .maf alignment file. Any ideas on what might be causing this?

**Comment by davevanins** [comment]
Salutations! Usually when this script fails at that location it is because 'full_seqdict' is empty, most commonly because the name of the reference genome does not match any of the sequence names in the .maf file. 

Can you check to make sure the "ref_contig" value you entered in the parameters file match the entry in the .maf file? 

Here is an example from a .maf file I generated where the ref_iso is "**M1630**" and the ref_contig is "**M1630_NODE1**"

##maf version=1 scoring=mugsy
a score=161811 label=1 mult=12
s **M1630**.**M1630_NODE1**		241901 150046 + 1717013 TGATTGGAGGAACAAAACCCCAAATC...
s M162.M162_NODE3		1179535 161411 + 2645252 TGATTGGAGGAACAAAACCCCAAAT...
s M164.M164_NODE2		1107531 161764 + 2586647 TGATTGGAGGAACAAAACCCCAAAT...

**Comment by asierzaragoza** [comment]
Thank you for the quick reply! The error was indeed caused by a typo in the ref_contig value.

**Comment by kaumudiprabhakara** [comment]
Hello, 
I have the same error, but somewhat different circumstances.  When running `phybreak2.maf_to_fasta.py`, I get the error 

```
Traceback (most recent call last):
  File "phybreak2.maf_to_fasta.py", line 341, in <module>
    corefile.write(">"+iso +"\n"+ full_seqdict[iso] +"\n")
KeyError: 'U420'
```

However, my **ref_iso** is **U140** and my **ref_contig** is **U140_lordec** 

i.e. the U140.fasta starts this way: 
```
>U140_lordec
GTGTCAGTGGAACTTTGGCAGCAGTGCGTGGAGCTTTT.... 
```
The beginning of my maf file looks like this:

```
##maf version=1 scoring=mugsy
a score=93422 label=1 mult=22
s PSE602i.PSE602i_1             144055 85752 + 1101321 -------------------------------------------------------------GGGGGCAAGCCCCC...
s MAFF311094.MAFF311094_1               5041619 85747 + 7043431 -------------------------------------------------------------GGGGGCAAGC...
s PSE602C.PSE602C_1             464492 85753 - 1330905 -------------------------------------------------------------GGGGGCAAGCCCCCTCC...
s PA_2_2B.PA_2_2B_1             4565136 85625 + 6649148 -------------------------------------------------------------GGGGGCAAGCCCC...
s SR17.SR17_1           4917634 85739 + 6856975 -------------------------------------------------------------GGGGGCAAGCCCCCT...
s U114.U114_1           4789511 85503 + 6737601 -------------------------------------------------------------GGGGGCAAGCCCC...
s U403.U403_14          81598 85573 + 182730 -------------------------------------------------------------GGGGGCAAGCCCCCTCCCACAGTTA...
s PS92.PS92_1           4845020 85649 + 6799674 -------------------------------------------------------------GGGGGCAAGCC...
s p2E10.p2E10_1         4828375 85644 + 6812763 -------------------------------------------------------------GGGGGCAAGCCCCCTCC...
s H14.H14_31            52689 85653 - 296287 GGGGGCTTGCCCCCG...
s M14.M14_1             5655477 85604 + 6927963 ----------------------------------------------------------------------------------GTTACGGTATTTACAGG...
s SBW25.SBW25_1         4794004 85340 + 6722400 --------------------------------------------------------------GGGGCAAGCCCCCTCC...
s U140.U140_1           4517951 85753 + 6540056 -------------------------------------------------------------GGGGGCTTGC...
s LMG6434t.LMG6434t_1           4660379 85782 + 6610222 -------------------------------------------------------------GGGGGCAAGC...
s PS720.PS720_22                24067 85644 + 109711 -------------------------------------------------------------GGGGGCAAGCCCC...
s OV546.OV546_6         50898 85627 - 376969 GGGGGCTTG...
s U257.U257_1           119322 86200 + 966214 -------------------------------------------------------------GGGGGCAAGCCCCC...
s U259.U259_1           187016 85687 - 697048 GGGGGCTTGCCCCCGA...
s QC2.QC2_18            94407 85601 + 351151 -------------------------------------------------------------GGGGGCAAGCCCC...
s U420.U420_2           140488 85752 - 917493 -------------------------------------------------------------GGGGGCAAGCCCCCTCCC...
s U299.U299_8           149126 85846 + 307712 -------------------------------------------------------------GGGGGCAAG...
s U416.U416_10          123067 85788 - 280777 GGGGGCTTGCCCCCG...
```

Note that in most of my fasta files, the contigs do not begin with the genome name, i.e., for example, the U420.fasta file starts like this:

```
>NODE_1_length_930550_cov_130.788654
CGGATATGTACCCTGTCTGATCCAACATCCAGGTCAGCCGTCAGGCCGCCACGG...
```

Could this be the problem? I am not sure where my mistake is. I would be grateful for any advice. 

Thank you!

UPDATE: I modified my fasta files so that the contigs are name_of_the_genome_0, name_of_the_genome_2 etc.  and reran everything. But I still get the same error.
