### ISSUE TITLE
PopCOGenT run error

### ISSUE THREAD

**Issue by Diamonds95** [philarevalo/PopCOGenT#9]
I had run PopCOGenT.sh successfully before, but when I use another dataset it failed, the error message is :
Traceback (most recent call last):
  File "cluster.py", line 315, in <module>
    main()
  File "cluster.py", line 70, in main
    linear_model=negative_selection_linear_fit())
  File "cluster.py", line 298, in make_edgefile
    n2 = ','.join(clonal_components[n2])
TypeError: sequence item 0: expected str instance, numpy.int64 found
Is there any special requirements for input fasta_file name?

**Comment by philarevalo** [comment]
Yes, I think this is an issue with the genome names being interpreted as integers and not strings. Do your genome filenames only have numbers (aside from the .fasta extension)? 

I should be able to have a fix out for this, but unfortunately I probably won't be able to get to it for at least a week.

**Comment by Diamonds95** [comment]
Thanks for your reply! Yes , all my fasta file were named by only numbers. Maybe I can rename them and try again!
